### ISSUE TITLE
Select uppercase not working

### ISSUE THREAD

**Issue by janahmonsanto** [budjako/aDB#23]
**UPPER CASE**
![image](https://user-images.githubusercontent.com/22288821/33050470-0c23da02-cea0-11e7-9d98-765c280ff437.png)

**LOWER CASE**
![image](https://user-images.githubusercontent.com/22288821/33050504-2763fdec-cea0-11e7-8695-1e6378dd8893.png)

**Comment by janahmonsanto** [comment]
Only works when string is lowercase

**Comment by aplanacay** [comment]
converted selText to lower case to fix this
